"""modified breaincoachresponses

Revision ID: 06b4f53879c2
Revises: bc7d67649d0a
Create Date: 2025-08-26 14:27:40.281597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b4f53879c2'
down_revision = 'bc7d67649d0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brain_coach_responses', sa.Column('session_id', sa.String(length=20), nullable=False))
    op.alter_column('brain_coach_responses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brain_coach_responses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('brain_coach_responses', 'session_id')
    # ### end Alembic commands ###