"""added post call tables and batch table

Revision ID: 0981c7894617
Revises: dba527be840f
Create Date: 2025-09-14 01:17:25.441702+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0981c7894617'
down_revision = 'dba527be840f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_eleven_labs_batch_calls_id', table_name='eleven_labs_batch_calls')
    op.drop_table('eleven_labs_batch_calls')
    op.drop_index('ix_eleven_labs_sessions_id', table_name='eleven_labs_sessions')
    op.drop_table('eleven_labs_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eleven_labs_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('call_successful', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('termination_reason', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transcription', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='eleven_labs_sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='eleven_labs_sessions_pkey')
    )
    op.create_index('ix_eleven_labs_sessions_id', 'eleven_labs_sessions', ['id'], unique=False)
    op.create_table('eleven_labs_batch_calls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('checked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='eleven_labs_batch_calls_pkey')
    )
    op.create_index('ix_eleven_labs_batch_calls_id', 'eleven_labs_batch_calls', ['id'], unique=False)
    # ### end Alembic commands ###