"""default

Revision ID: 369b504b2e7c
Revises: dc3c904fc1bf
Create Date: 2025-11-08 09:38:32.017833+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '369b504b2e7c'
down_revision = 'dc3c904fc1bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_id', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_onboarding_users_id', table_name='onboarding_users')
    op.drop_index('ix_onboarding_users_phone_number', table_name='onboarding_users')
    op.drop_table('onboarding_users')
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('whatsapp_reports', sa.Boolean(), nullable=True, default=False))
    op.add_column('users', sa.Column('email_reports', sa.Boolean(), nullable=True, default=False))
    op.add_column('users', sa.Column('preferred_communication_channel', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_communication_channel')
    op.drop_column('users', 'email_reports')
    op.drop_column('users', 'whatsapp_reports')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'date_of_birth')
    op.create_table('onboarding_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('preferred_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('preferred_communication_channel', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email_reports', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('whatsapp_reports', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('onboarding_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('onboarded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('called_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='onboarding_users_pkey')
    )
    op.create_index('ix_onboarding_users_phone_number', 'onboarding_users', ['phone_number'], unique=False)
    op.create_index('ix_onboarding_users_id', 'onboarding_users', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=20), autoincrement=False, nullable=False, default='UTC'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('onboarding_agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, default=True),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey')
    )
    op.create_index('ix_organizations_id', 'organizations', ['id'], unique=False)
    # ### end Alembic commands ###