"""added post call tables and batch table again

Revision ID: 36a37ce9f2fa
Revises: 0981c7894617
Create Date: 2025-09-14 01:17:54.025193+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a37ce9f2fa'
down_revision = '0981c7894617'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eleven_labs_batch_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=30), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eleven_labs_batch_calls_id'), 'eleven_labs_batch_calls', ['id'], unique=False)
    op.create_table('eleven_labs_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_successful', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.String(length=80), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('termination_reason', sa.String(length=40), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transcription', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eleven_labs_sessions_id'), 'eleven_labs_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eleven_labs_sessions_id'), table_name='eleven_labs_sessions')
    op.drop_table('eleven_labs_sessions')
    op.drop_index(op.f('ix_eleven_labs_batch_calls_id'), table_name='eleven_labs_batch_calls')
    op.drop_table('eleven_labs_batch_calls')
    # ### end Alembic commands ###