"""added caretaker fields to user

Revision ID: 3cd2ca7eeb6b
Revises: 5c4bf6cf6985
Create Date: 2025-09-10 07:08:26.213413+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3cd2ca7eeb6b'
down_revision = '5c4bf6cf6985'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medications', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('medications', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_column('medications', 'frequency')
    op.add_column('users', sa.Column('preffered_channel', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('caretaker_preferred_channel', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('caretaker_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('caretaker_phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'caretaker_phone_number')
    op.drop_column('users', 'caretaker_email')
    op.drop_column('users', 'caretaker_preferred_channel')
    op.drop_column('users', 'preffered_channel')
    op.add_column('medications', sa.Column('frequency', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('medications', 'end_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('medications', 'start_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###