"""added multi lingual support in questions

Revision ID: 500b40f8d54d
Revises: 2ef375fcbea5
Create Date: 2025-09-01 12:08:37.436962+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500b40f8d54d'
down_revision = '2ef375fcbea5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brain_coach_questions', sa.Column('max_score', sa.Integer(), nullable=True))
    op.drop_column('brain_coach_questions', 'scoring_logic')
    op.drop_column('brain_coach_questions', 'question_type')
    op.drop_column('brain_coach_questions', 'expected_answer')
    op.drop_column('brain_coach_questions', 'theme')
    op.drop_column('brain_coach_questions', 'question')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brain_coach_questions', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('brain_coach_questions', sa.Column('theme', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('brain_coach_questions', sa.Column('expected_answer', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('brain_coach_questions', sa.Column('question_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('brain_coach_questions', sa.Column('scoring_logic', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('brain_coach_questions', 'max_score')
    # ### end Alembic commands ###