"""made session nullable for development

Revision ID: 80319e3b69fe
Revises: d5b68b995615
Create Date: 2025-09-09 05:02:19.006985+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80319e3b69fe'
down_revision = 'd5b68b995615'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brain_coach_responses', 'session_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brain_coach_responses', 'session_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###