"""Add user_id foreign key to medications table

Revision ID: 85677eb93283
Revises: 0ee64b199755
Create Date: 2025-09-08 06:16:20.406910+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85677eb93283'
down_revision = '0ee64b199755'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'medications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medications', type_='foreignkey')
    op.drop_column('medications', 'user_id')
    # ### end Alembic commands ###