"""added social scheme

Revision ID: bc7d67649d0a
Revises: 
Create Date: 2025-08-26 11:49:15.905274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7d67649d0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brain_coach_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.Column('scoring_logic', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_coach_questions_id'), 'brain_coach_questions', ['id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('living_situation', sa.Enum('ALONE', 'WITH_PARTNER', 'WITH_FAMILY', name='livingsituation'), nullable=True),
    sa.Column('social_check_ins', sa.Boolean(), nullable=True),
    sa.Column('faith_tradition', sa.Enum('CHRISTIANITY', 'ISLAM', 'JUDAISM', 'HINDUISM', 'BUDDHISM', 'OTHER', 'PREFER_NOT_TO_SAY', name='faithtraditionenum'), nullable=True),
    sa.Column('local_event_recommendations', sa.Boolean(), nullable=True),
    sa.Column('preferred_check_in_time', sa.Enum('EARLY_MORNING', 'LATE_MORNING', 'EARLY_AFTERNOON', 'LATE_AFTERNOON', 'EVENING', 'NIGHT', name='preferredcheckintimeenum'), nullable=True),
    sa.Column('check_in_frequency', sa.Enum('MULTIPLE_PER_DAY', 'DAILY', 'SEVERAL_PER_WEEK', 'WEEKLY', 'EMERGENCIES_ONLY', 'WEEKENDS_ONLY', 'HOLIDAYS', name='checkinfrequencyenum'), nullable=True),
    sa.Column('wants_caretaker_alerts', sa.Boolean(), nullable=True),
    sa.Column('wants_reminders', sa.Boolean(), nullable=True),
    sa.Column('takes_medication', sa.Boolean(), nullable=True),
    sa.Column('missed_dose_alerts', sa.Boolean(), nullable=True),
    sa.Column('escalate_to_emergency_contact', sa.Boolean(), nullable=True),
    sa.Column('medical_devices', sa.Text(), nullable=True),
    sa.Column('mobility', sa.Enum('INDEPENDENT', 'WALK_WITH_ASSISTANCE', 'WHEELCHAIR', 'BED_BOUND', name='mobilityenum'), nullable=True),
    sa.Column('telehealth_activation', sa.Boolean(), nullable=True),
    sa.Column('preferred_doctor_type', sa.Enum('MY_OWN', 'ANY_AVAILABLE', 'SPECIALIST', name='preferreddoctortypeenum'), nullable=True),
    sa.Column('preferred_consultation_type', sa.Enum('PHONE', 'VIDEO', name='preferredconsultationtypeenum'), nullable=True),
    sa.Column('preferred_consultation_language', sa.Enum('ENGLISH', 'SPANISH', 'GERMAN', 'FRENCH', 'OTHER', name='preferredconsultationlanguageenum'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('brain_coach_activation', sa.Boolean(), nullable=True),
    sa.Column('brain_coach_time', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', name='braincoachtimeenum'), nullable=True),
    sa.Column('brain_coach_complexity', sa.Enum('EASY', 'MEDIUM', 'ADVANCED', 'PROGRESSIVE', name='braincoachcomplexityenum'), nullable=True),
    sa.Column('performance_reports', sa.Boolean(), nullable=True),
    sa.Column('cognitive_decline_alerts', sa.Boolean(), nullable=True),
    sa.Column('fall_detection_activation', sa.Boolean(), nullable=True),
    sa.Column('fall_auto_alert_to_caregiver', sa.Boolean(), nullable=True),
    sa.Column('regular_safety_check_ins', sa.Enum('DAILY', 'TWICE_DAILY', name='regularsafetycheckinsenum'), nullable=True),
    sa.Column('primary_doctor_name', sa.String(length=255), nullable=True),
    sa.Column('primary_doctor_phone', sa.String(length=20), nullable=True),
    sa.Column('preferred_pharmacy_name', sa.String(length=255), nullable=True),
    sa.Column('preferred_pharmacy_phone', sa.String(length=20), nullable=True),
    sa.Column('preferred_hospital_name', sa.String(length=255), nullable=True),
    sa.Column('preferred_hospital_phone', sa.String(length=20), nullable=True),
    sa.Column('device_token', sa.String(length=150), nullable=True),
    sa.Column('expiration', sa.String(length=50), nullable=True),
    sa.Column('p256dh', sa.String(length=100), nullable=True),
    sa.Column('auth', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('TopicOfInterest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('NEWS', 'MUSIC', 'COOKING', 'SPORTS', 'GARDENING', 'READING', 'HISTORY', 'TECH', 'TRAVEL', 'MOVIES', 'ARTS', 'PETS', 'FAMILY', 'WELLNESS', 'OTHER', name='topicenum'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TopicOfInterest_id'), 'TopicOfInterest', ['id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('MUSIC', 'BRAIN_GAMES', 'STORYTELLING', 'RELAXATION', 'LEARNING', 'RECIPES', 'EXERCISE', 'NEUTRAL_INSPIRATION', 'FAITH_BASED_INSPIRATION', 'OTHER', name='activityenum'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('brain_coach_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['brain_coach_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_coach_responses_id'), 'brain_coach_responses', ['id'], unique=False)
    op.create_table('long_term_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('DIABETES', 'HEART_DISEASE', 'HYPERTENSION', 'HIGH_CHOLESTEROL', 'STROKE', 'ARTHRITIS', 'OSTEOPOROSIS', 'RESPIRATORY_DISEASE', 'CANCER', 'KIDNEY_DISEASE', 'LIVER_DISEASE', 'ALZHEIMERS', 'DEMENTIA', 'PARKINSONS', 'ANXIETY', 'DEPRESSION', 'VISION_PROBLEMS', 'HEARING_LOSS', 'CHRONIC_PAIN', 'MOBILITY_IMPAIRMENT', 'OTHER', name='longtermconditionenum'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_long_term_conditions_id'), 'long_term_conditions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_long_term_conditions_id'), table_name='long_term_conditions')
    op.drop_table('long_term_conditions')
    op.drop_index(op.f('ix_brain_coach_responses_id'), table_name='brain_coach_responses')
    op.drop_table('brain_coach_responses')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_TopicOfInterest_id'), table_name='TopicOfInterest')
    op.drop_table('TopicOfInterest')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_brain_coach_questions_id'), table_name='brain_coach_questions')
    op.drop_table('brain_coach_questions')
    # ### end Alembic commands ###