"""restructure, onboarding, caretaker addition

Revision ID: bf1b2d0c0f7a
Revises: da39cb72f0c3
Create Date: 2025-11-17 06:47:01.575474+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf1b2d0c0f7a'
down_revision = 'da39cb72f0c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caretakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_caretakers_id'), 'caretakers', ['id'], unique=False)
    op.drop_index('ix_TopicOfInterest_id', table_name='TopicOfInterest')
    op.drop_table('TopicOfInterest')
    op.drop_index('ix_activities_id', table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_long_term_conditions_id', table_name='long_term_conditions')
    op.drop_table('long_term_conditions')
    op.drop_index('ix_onboarding_users_id', table_name='onboarding_users')
    op.drop_index('ix_onboarding_users_phone_number', table_name='onboarding_users')
    op.drop_table('onboarding_users')
    op.add_column('users', sa.Column('land_line', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('health_conditions', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('faith', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('topics_of_interest', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('preferred_activities', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('caretaker_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_name', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('nutrition_services_activation', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('concierge_services_activation', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('scam_protection_activation', sa.Boolean(), nullable=True))
    op.alter_column('users', 'mobility',
               existing_type=postgresql.ENUM('INDEPENDENT', 'WALK_WITH_ASSISTANCE', 'WHEELCHAIR', 'BED_BOUND', name='mobilityenum'),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'whatsapp_reports',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'email_reports',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_users_caretaker_id'), 'users', ['caretaker_id'], unique=False)
    op.create_foreign_key(None, 'users', 'caretakers', ['caretaker_id'], ['id'])
    op.drop_column('users', 'regular_safety_check_ins')
    op.drop_column('users', 'preferred_pharmacy_name')
    op.drop_column('users', 'caretaker_phone_number')
    op.drop_column('users', 'medical_devices')
    op.drop_column('users', 'caretaker_preferred_channel')
    op.drop_column('users', 'preferred_consultation_type')
    op.drop_column('users', 'faith_tradition')
    op.drop_column('users', 'preferred_hospital_phone')
    op.drop_column('users', 'cognitive_decline_alerts')
    op.drop_column('users', 'primary_doctor_phone')
    op.drop_column('users', 'preferred_pharmacy_phone')
    op.drop_column('users', 'caretaker_name')
    op.drop_column('users', 'telehealth_activation')
    op.drop_column('users', 'primary_doctor_name')
    op.drop_column('users', 'preferred_hospital_name')
    op.drop_column('users', 'caretaker_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('caretaker_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_hospital_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('primary_doctor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('telehealth_activation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('caretaker_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_pharmacy_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('primary_doctor_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('cognitive_decline_alerts', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_hospital_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('faith_tradition', postgresql.ENUM('CHRISTIANITY', 'ISLAM', 'JUDAISM', 'HINDUISM', 'BUDDHISM', 'OTHER', 'PREFER_NOT_TO_SAY', name='faithtraditionenum'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_consultation_type', postgresql.ENUM('PHONE', 'VIDEO', name='preferredconsultationtypeenum'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('caretaker_preferred_channel', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('medical_devices', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('caretaker_phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_pharmacy_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('regular_safety_check_ins', postgresql.ENUM('DAILY', 'TWICE_DAILY', name='regularsafetycheckinsenum'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_caretaker_id'), table_name='users')
    op.alter_column('users', 'email_reports',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'whatsapp_reports',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'mobility',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('INDEPENDENT', 'WALK_WITH_ASSISTANCE', 'WHEELCHAIR', 'BED_BOUND', name='mobilityenum'),
               existing_nullable=True)
    op.drop_column('users', 'scam_protection_activation')
    op.drop_column('users', 'concierge_services_activation')
    op.drop_column('users', 'nutrition_services_activation')
    op.drop_column('users', 'emergency_contact_phone')
    op.drop_column('users', 'emergency_contact_email')
    op.drop_column('users', 'emergency_contact_name')
    op.drop_column('users', 'caretaker_id')
    op.drop_column('users', 'preferred_activities')
    op.drop_column('users', 'topics_of_interest')
    op.drop_column('users', 'faith')
    op.drop_column('users', 'health_conditions')
    op.drop_column('users', 'land_line')
    op.create_table('onboarding_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('preferred_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('preferred_communication_channel', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email_reports', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('whatsapp_reports', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('onboarding_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('onboarded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('called_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='onboarding_users_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='onboarding_users_pkey')
    )
    op.create_index('ix_onboarding_users_phone_number', 'onboarding_users', ['phone_number'], unique=False)
    op.create_index('ix_onboarding_users_id', 'onboarding_users', ['id'], unique=False)
    op.create_table('long_term_conditions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', postgresql.ENUM('DIABETES', 'HEART_DISEASE', 'HYPERTENSION', 'HIGH_CHOLESTEROL', 'STROKE', 'ARTHRITIS', 'OSTEOPOROSIS', 'RESPIRATORY_DISEASE', 'CANCER', 'KIDNEY_DISEASE', 'LIVER_DISEASE', 'ALZHEIMERS', 'DEMENTIA', 'PARKINSONS', 'ANXIETY', 'DEPRESSION', 'VISION_PROBLEMS', 'HEARING_LOSS', 'CHRONIC_PAIN', 'MOBILITY_IMPAIRMENT', 'OTHER', name='longtermconditionenum'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='long_term_conditions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='long_term_conditions_pkey'),
    sa.UniqueConstraint('name', name='long_term_conditions_name_key')
    )
    op.create_index('ix_long_term_conditions_id', 'long_term_conditions', ['id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', postgresql.ENUM('MUSIC', 'BRAIN_GAMES', 'STORYTELLING', 'RELAXATION', 'LEARNING', 'RECIPES', 'EXERCISE', 'NEUTRAL_INSPIRATION', 'FAITH_BASED_INSPIRATION', 'OTHER', name='activityenum'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='activities_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='activities_pkey')
    )
    op.create_index('ix_activities_id', 'activities', ['id'], unique=False)
    op.create_table('TopicOfInterest',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"TopicOfInterest_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', postgresql.ENUM('NEWS', 'MUSIC', 'COOKING', 'SPORTS', 'GARDENING', 'READING', 'HISTORY', 'TECH', 'TRAVEL', 'MOVIES', 'ARTS', 'PETS', 'FAMILY', 'WELLNESS', 'OTHER', name='topicenum'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='TopicOfInterest_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='TopicOfInterest_pkey')
    )
    op.create_index('ix_TopicOfInterest_id', 'TopicOfInterest', ['id'], unique=False)
    op.drop_index(op.f('ix_caretakers_id'), table_name='caretakers')
    op.drop_table('caretakers')
    # ### end Alembic commands ###