"""added medication tables

Revision ID: cfe57d6cdd48
Revises: 500b40f8d54d
Create Date: 2025-09-07 14:31:14.442461+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe57d6cdd48'
down_revision = '500b40f8d54d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=True),
    sa.Column('notes', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_times_id'), 'medication_times', ['id'], unique=False)
    op.add_column('medications', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('medications', sa.Column('dosage', sa.String(length=100), nullable=False))
    op.add_column('medications', sa.Column('frequency', sa.String(length=100), nullable=False))
    op.add_column('medications', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('medications', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('medications', sa.Column('purpose', sa.Text(), nullable=True))
    op.add_column('medications', sa.Column('side_effects', sa.Text(), nullable=True))
    op.add_column('medications', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'notes')
    op.drop_column('medications', 'side_effects')
    op.drop_column('medications', 'purpose')
    op.drop_column('medications', 'end_date')
    op.drop_column('medications', 'start_date')
    op.drop_column('medications', 'frequency')
    op.drop_column('medications', 'dosage')
    op.drop_column('medications', 'name')
    op.drop_index(op.f('ix_medication_times_id'), table_name='medication_times')
    op.drop_table('medication_times')
    # ### end Alembic commands ###