"""default

Revision ID: da39cb72f0c3
Revises: 369b504b2e7c
Create Date: 2025-11-08 12:11:03.811508+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da39cb72f0c3'
down_revision = '369b504b2e7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_onboarding_users_id', table_name='onboarding_users')
    op.drop_index('ix_onboarding_users_phone_number', table_name='onboarding_users')
    op.drop_table('onboarding_users')
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'whatsapp_reports',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'email_reports',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'email_reports',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'whatsapp_reports',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'organization_id')
    op.create_table('onboarding_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('preferred_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('preferred_communication_channel', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email_reports', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('whatsapp_reports', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('onboarding_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('onboarded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('called_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='onboarding_users_pkey')
    )
    op.create_index('ix_onboarding_users_phone_number', 'onboarding_users', ['phone_number'], unique=False)
    op.create_index('ix_onboarding_users_id', 'onboarding_users', ['id'], unique=False)
    # ### end Alembic commands ###