"""fixed preffered column name in users

Revision ID: dba527be840f
Revises: 3cd2ca7eeb6b
Create Date: 2025-09-11 09:39:24.417347+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba527be840f'
down_revision = '3cd2ca7eeb6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_channel', sa.String(length=50), nullable=True))
    op.drop_column('users', 'preffered_channel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preffered_channel', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'preferred_channel')
    # ### end Alembic commands ###