"""added caretaker name

Revision ID: dc3c904fc1bf
Revises: 36a37ce9f2fa
Create Date: 2025-09-19 03:53:51.745355+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3c904fc1bf'
down_revision = '36a37ce9f2fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('caretaker_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'caretaker_name')
    # ### end Alembic commands ###