"""Add enhanced symptom fields to symptom_checker_responses

Revision ID: de2b6e6ba602
Revises: 500b40f8d54d
Create Date: 2025-09-07 17:26:25.681104+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2b6e6ba602'
down_revision = '500b40f8d54d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symptom_checker_responses', sa.Column('heart_rate', sa.String(length=20), nullable=True))
    op.add_column('symptom_checker_responses', sa.Column('severity_scale', sa.String(length=20), nullable=True))
    op.add_column('symptom_checker_responses', sa.Column('duration', sa.String(length=100), nullable=True))
    op.add_column('symptom_checker_responses', sa.Column('respiratory_rate', sa.String(length=20), nullable=True))
    op.add_column('symptom_checker_responses', sa.Column('additional_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symptom_checker_responses', 'additional_notes')
    op.drop_column('symptom_checker_responses', 'respiratory_rate')
    op.drop_column('symptom_checker_responses', 'duration')
    op.drop_column('symptom_checker_responses', 'severity_scale')
    op.drop_column('symptom_checker_responses', 'heart_rate')
    # ### end Alembic commands ###