"""added brain coach questions model, repo, and endpoint

Revision ID: e3aed407dd19
Revises: d0386d564dd3
Create Date: 2025-08-23 03:43:59.354523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3aed407dd19'
down_revision = 'd0386d564dd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brain_coach_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.Column('scoring_logic', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_coach_questions_id'), 'brain_coach_questions', ['id'], unique=False)
    op.create_table('brain_coach_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['brain_coach_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_coach_responses_id'), 'brain_coach_responses', ['id'], unique=False)
    op.drop_index('ix_brain_coach_id', table_name='brain_coach')
    op.drop_table('brain_coach')
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('living_situation', sa.Enum('ALONE', 'WITH_PARTNER', 'WITH_FAMILY', name='livingsituation'), nullable=True))
    op.add_column('users', sa.Column('wants_caretaker_alerts', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('wants_reminders', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('takes_medication', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('missed_dose_alerts', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('escalate_to_emergency_contact', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('medical_devices', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('mobility', sa.Enum('INDEPENDENT', 'WALK_WITH_ASSISTANCE', 'WHEELCHAIR', 'BED_BOUND', name='mobilityenum'), nullable=True))
    op.add_column('users', sa.Column('telehealth_activation', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('preferred_doctor_type', sa.Enum('MY_OWN', 'ANY_AVAILABLE', 'SPECIALIST', name='preferreddoctortypeenum'), nullable=True))
    op.add_column('users', sa.Column('preferred_consultation_type', sa.Enum('PHONE', 'VIDEO', name='preferredconsultationtypeenum'), nullable=True))
    op.add_column('users', sa.Column('preferred_consultation_language', sa.Enum('ENGLISH', 'SPANISH', 'GERMAN', 'FRENCH', 'OTHER', name='preferredconsultationlanguageenum'), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('brain_coach_activation', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('brain_coach_time', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', name='braincoachtimeenum'), nullable=True))
    op.add_column('users', sa.Column('brain_coach_complexity', sa.Enum('EASY', 'MEDIUM', 'ADVANCED', 'PROGRESSIVE', name='braincoachcomplexityenum'), nullable=True))
    op.add_column('users', sa.Column('performance_reports', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('cognitive_decline_alerts', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('fall_detection_activation', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('fall_auto_alert_to_caregiver', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('regular_safety_check_ins', sa.Enum('DAILY', 'TWICE_DAILY', name='regularsafetycheckinsenum'), nullable=True))
    op.add_column('users', sa.Column('primary_doctor_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('primary_doctor_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('preferred_pharmacy_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('preferred_pharmacy_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('preferred_hospital_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('preferred_hospital_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('device_token', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('expiration', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('p256dh', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('auth', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'auth')
    op.drop_column('users', 'p256dh')
    op.drop_column('users', 'expiration')
    op.drop_column('users', 'device_token')
    op.drop_column('users', 'preferred_hospital_phone')
    op.drop_column('users', 'preferred_hospital_name')
    op.drop_column('users', 'preferred_pharmacy_phone')
    op.drop_column('users', 'preferred_pharmacy_name')
    op.drop_column('users', 'primary_doctor_phone')
    op.drop_column('users', 'primary_doctor_name')
    op.drop_column('users', 'regular_safety_check_ins')
    op.drop_column('users', 'fall_auto_alert_to_caregiver')
    op.drop_column('users', 'fall_detection_activation')
    op.drop_column('users', 'cognitive_decline_alerts')
    op.drop_column('users', 'performance_reports')
    op.drop_column('users', 'brain_coach_complexity')
    op.drop_column('users', 'brain_coach_time')
    op.drop_column('users', 'brain_coach_activation')
    op.drop_column('users', 'country')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'city')
    op.drop_column('users', 'street')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'preferred_consultation_language')
    op.drop_column('users', 'preferred_consultation_type')
    op.drop_column('users', 'preferred_doctor_type')
    op.drop_column('users', 'telehealth_activation')
    op.drop_column('users', 'mobility')
    op.drop_column('users', 'medical_devices')
    op.drop_column('users', 'escalate_to_emergency_contact')
    op.drop_column('users', 'missed_dose_alerts')
    op.drop_column('users', 'takes_medication')
    op.drop_column('users', 'wants_reminders')
    op.drop_column('users', 'wants_caretaker_alerts')
    op.drop_column('users', 'living_situation')
    op.drop_column('users', 'age')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'email')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.create_table('brain_coach',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='brain_coach_pkey')
    )
    op.create_index('ix_brain_coach_id', 'brain_coach', ['id'], unique=False)
    op.drop_index(op.f('ix_brain_coach_responses_id'), table_name='brain_coach_responses')
    op.drop_table('brain_coach_responses')
    op.drop_index(op.f('ix_brain_coach_questions_id'), table_name='brain_coach_questions')
    op.drop_table('brain_coach_questions')
    # ### end Alembic commands ###